---
packages:
  - fish
  - most
  - neovim
  - python3
  - pip3
  - ansible
  - golang
  - vscode

fish:
  fisher: curl https://git.io/fisher --create-dirs -sLo ~/.config/fish/functions/fisher.fish
  theme: fisher add oh-my-fish/theme-bobthefish
  custom:
    - aliases.fish
    - env.fish
    - golang.fish
    - pier39.fish
    - python.fish

dotfiles:
  tmux:
    conf: .tumx.conf
    sessions:
      - default
      - 4-panes

pip:
  - mitogen