[settings]
ignored_config_paths = ["$HOME/dotfiles/mise/config.toml"]
idiomatic_version_file_enable_tools = []

[tools]
age = "latest"
awscli = "latest"
bat = "latest"
bun = "latest"
"cargo:https://github.com/rtk-ai/rtk" = "tag:latest"
claude-code = "latest"
dagger = "latest"
delta = "latest"
"cargo:difftastic" = "latest"
duf = "latest"
dust = "latest"
fd = "latest"
fzf = "latest"
gcloud = "latest"
gemini = "latest"
gh = "latest"
github-cli = "latest"
gitui = "latest"
glab = "latest"
helm = "latest"
java = "latest"
k9s = "latest"
kubecolor = "latest"
kubectl = "latest"
kubectx = "latest"
lazygit = "latest"
lsd = "latest"
minikube = "latest"
neovim = "latest"
node = "latest"
python = "latest"
rg = "latest"
ruby = "latest"
ruff = "latest"
rust = "latest"
slsa-verifier = "latest"
sops = "latest"
starship = "latest"
talosctl = "latest"
usage = "latest"
uv = "latest"
xh = "latest"
zellij = "latest"
"cargo:llmfit" = "latest"
"cargo:llmserve" = "latest"

[env]
# Install seed packages (pip, setuptools, and wheel) into the virtual environment.
_.python.venv = { path = "{{env.HOME}}/.venv", create = true, uv_create_args = ["--no-cache", "--no-config", "--no-managed-python", "--no-workspace", "--seed", "--refresh"] }

[settings.npm]
package_manager = "bun"
