[tools]
age = "latest"
awscli = "latest"
bat = "latest"
cilium-cli = "latest"
cosign = "latest"
dagger = "latest"
delta = "latest"
difftastic = "latest"
dust = "latest"
fd = "latest"
gcloud = "latest"
gitui = "latest"
helm = "latest"
java = "latest"
k9s = "latest"
kubecolor = "latest"
kubectl = "latest"
lsd = "latest"
minikube = "latest"
neovim = "latest"
python = "latest"
rg = "latest"
ruff = "latest"
rust = "latest"
slsa-verifier = "latest"
sops = "latest"
starship = "latest"
usage = "latest"
uv = "latest"
xh = "latest"
zellij = "latest"

[env]
# Install seed packages (pip, setuptools, and wheel) into the virtual environment.
_.python.venv = { path = "{{env.HOME}}/.venv", create = true, uv_create_args = ["--no-cache", "--no-config", "--no-managed-python", "--no-workspace", "--seed", "--refresh"] }
