[tools]
age = "latest"
bat = "latest"
cosign = "latest"
dust = "latest"
fd = "latest"
gcloud = "latest"
helix = "latest"
k9s = "latest"
kubecolor = "latest"
lsd = "latest"
python = "latest"
rg = "latest"
rust = "latest"
slsa-verifier = "latest"
sops = "latest"
starship = "latest"
uv = "latest"
xh = "latest"
zellij = "latest"
